ZVECTXF ; Fix: Add Wave 1 ZVE RPCs to OR CPRS GUI CHART context
 Q
RUN ;
 N CTXIEN S CTXIEN=$$FIND1^DIC(19,,"B","OR CPRS GUI CHART")
 I 'CTXIEN W "OR CPRS GUI CHART not found",! Q
 W "Context IEN: ",CTXIEN,!
 ;
 D ADD(CTXIEN,"ZVE USER LIST")
 D ADD(CTXIEN,"ZVE USER DETAIL")
 D ADD(CTXIEN,"ZVE USER EDIT")
 D ADD(CTXIEN,"ZVE USER TERM")
 D ADD(CTXIEN,"ZVE ADMIN AUDIT")
 D ADD(CTXIEN,"ZVE USER RENAME")
 D ADD(CTXIEN,"ZVE PATIENT REGISTER")
 D ADD(CTXIEN,"ZVE PATIENT EDIT")
 D ADD(CTXIEN,"ZVE PATIENT DEMOGRAPHICS")
 D ADD(CTXIEN,"ZVE PATIENT INSURANCE")
 D ADD(CTXIEN,"ZVE PATIENT MEANS")
 D ADD(CTXIEN,"ZVE PATIENT ELIG")
 D ADD(CTXIEN,"ZVE PATIENT FLAGS")
 D ADD(CTXIEN,"ZVE PATIENT DUPLICATE")
 D ADD(CTXIEN,"ZVE PATIENT SEARCH EXTENDED")
 D ADD(CTXIEN,"ZVE RECENT PATIENTS")
 D ADD(CTXIEN,"ZVE PATIENT DECEASED")
 D ADD(CTXIEN,"ZVE ADT ADMIT")
 D ADD(CTXIEN,"ZVE ADT DISCHARGE")
 D ADD(CTXIEN,"ZVE ADT TRANSFER")
 D ADD(CTXIEN,"ZVE ADT CENSUS")
 W !,"Done — ",$$CNT(CTXIEN)," total RPCs in context",!
 Q
 ;
ADD(CTXIEN,RPCNAME) ;
 N RPCIEN S RPCIEN=$$FIND1^DIC(8994,,"B",RPCNAME)
 I 'RPCIEN W "  NOT FOUND: ",RPCNAME,! Q
 ; Check duplicate
 N I S I=0
 F  S I=$O(^DIC(19,CTXIEN,"RPC",I)) Q:'I  D  Q:$G(DUP)
 . I $P($G(^DIC(19,CTXIEN,"RPC",I,0)),U,1)=RPCIEN N DUP S DUP=1
 I $G(DUP) W "  ALREADY: ",RPCNAME,! Q
 ; Add
 N NIEN S NIEN=$P($G(^DIC(19,CTXIEN,"RPC",0)),U,3)+1
 S ^DIC(19,CTXIEN,"RPC",NIEN,0)=RPCIEN
 S $P(^DIC(19,CTXIEN,"RPC",0),U,3)=NIEN
 S $P(^DIC(19,CTXIEN,"RPC",0),U,4)=$P(^DIC(19,CTXIEN,"RPC",0),U,4)+1
 W "  ADDED: ",RPCNAME," (RPC IEN=",RPCIEN,")",!
 Q
 ;
CNT(CTXIEN) ;
 N C,I S C=0,I=0
 F  S I=$O(^DIC(19,CTXIEN,"RPC",I)) Q:'I  S C=C+1
 Q C
