ZVECTX2 ; VE — Create Admin/Patient contexts + register Wave 1 RPCs ; Apr 2026
 ;;1.0;VISTA EVOLVED;**1**;Apr 2026;Build 1
 ;
 ; Creates two B-type context options in File #19:
 ;   ZVE ADMIN CONTEXT   — All admin/user management RPCs
 ;   ZVE PATIENT CONTEXT — All patient/ADT RPCs
 ; Then registers all Wave 1 RPCs into the appropriate context
 ;
 Q  ; No direct entry
 ;
RUN ;
 W !,"============================================"
 W !,"  Wave 1 Context Registration"
 W !,"============================================"
 ;
 ; Step 1: Create context options if they don't exist
 N ADMCTX,PATCTX
 S ADMCTX=$$GETCTX("ZVE ADMIN CONTEXT","VistA Evolved Admin Context")
 S PATCTX=$$GETCTX("ZVE PATIENT CONTEXT","VistA Evolved Patient Context")
 ;
 ; Step 2: Register Admin RPCs into ZVE ADMIN CONTEXT
 W !,""
 W !,"--- Admin Context RPCs ---"
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USER LIST")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USER DETAIL")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USER EDIT")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USER TERM")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE ADMIN AUDIT")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USER RENAME")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE KEY LIST")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE KEY ASSIGN")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE KEY REMOVE")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE ESIG MANAGE")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE ROLE TEMPLATE")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE PARAM GET")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE PARAM SET")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE DIVISION LIST")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE DIVISION ASSIGN")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE SITE WS GET")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE SITE WS SET")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE ROLE CUSTOM LIST")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE ROLE CUSTOM CRT")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE ROLE CUSTOM DEL")
 ;
 ; Also add existing ZVEUSMG RPCs to admin context
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG KEYS")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG ESIG")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG CRED")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG ADD")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG DEACT")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG REACT")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG RENAME")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USMG TERM")
 D ADDRPC^ZVECTXR(ADMCTX,"ZVE USER CLONE")
 ;
 ; Step 3: Register Patient RPCs into ZVE PATIENT CONTEXT
 W !,""
 W !,"--- Patient Context RPCs ---"
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT REGISTER")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT EDIT")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT DEMOGRAPHICS")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT INSURANCE")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT MEANS")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT ELIG")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT FLAGS")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT DUPLICATE")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT SEARCH EXTENDED")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE RECENT PATIENTS")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE PATIENT DECEASED")
 ;
 ; ADT RPCs also in Patient Context
 D ADDRPC^ZVECTXR(PATCTX,"ZVE ADT ADMIT")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE ADT DISCHARGE")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE ADT TRANSFER")
 D ADDRPC^ZVECTXR(PATCTX,"ZVE ADT CENSUS")
 ;
 W !,""
 W !,"============================================"
 W !,"  Context registration complete!"
 W !,"============================================"
 Q
 ;
GETCTX(NAME,DESC) ;
 ; Find or create a B-type context option in File #19
 ; Returns IEN of the context option
 N IEN S IEN=$$FIND1^DIC(19,,"BX",NAME)
 I IEN>0 D  Q IEN
 . W !,"Context found: ",NAME," (IEN=",IEN,")"
 ;
 ; Create option type B (Broker context)
 N FDA,DIERR,DIEN S DIEN(1)=""
 S FDA(19,"+1,",.01)=NAME
 S FDA(19,"+1,",1)=DESC
 S FDA(19,"+1,",4)="B" ; type = Broker
 D UPDATE^DIE("E","FDA","DIEN","DIERR")
 I $D(DIERR) D  Q 0
 . W !,"ERROR creating context ",NAME,": ",$G(DIERR("DIERR",1,"TEXT",1))
 ;
 S IEN=+DIEN(1)
 W !,"Context CREATED: ",NAME," (IEN=",IEN,")"
 Q IEN
