ZVECTXR ; VE — Register overlay RPCs into OR CPRS GUI CHART context
 ;;1.0;VE CTXR;**;Mar 21, 2026
 Q
 ;
RUN ; Entry point: add all ZVE RPCs to the OR CPRS GUI CHART context
 N CTXIEN
 S CTXIEN=$$FIND1^DIC(19,,"BX","OR CPRS GUI CHART")
 W !,"Context IEN: ",CTXIEN
 I CTXIEN<1 W !,"ERROR: OR CPRS GUI CHART not found" Q
 ;
 D ADDRPC(CTXIEN,"ZVE USMG KEYS")
 D ADDRPC(CTXIEN,"ZVE USMG ESIG")
 D ADDRPC(CTXIEN,"ZVE USMG CRED")
 D ADDRPC(CTXIEN,"ZVE USMG ADD")
 D ADDRPC(CTXIEN,"ZVE USMG DEACT")
 D ADDRPC(CTXIEN,"ZVE USMG REACT")
 D ADDRPC(CTXIEN,"ZVE CLNM ADD")
 D ADDRPC(CTXIEN,"ZVE CLNM EDIT")
 D ADDRPC(CTXIEN,"ZVE WRDM EDIT")
 W !,"=== Context registration complete ==="
 Q
 ;
ADDRPC(CTXIEN,RPCNAME) ; Add one RPC to the context
 N RPCIEN,FOUND,K,MAX
 S RPCIEN=$$FIND1^DIC(8994,,"BX",RPCNAME)
 I RPCIEN<1 W !,"  Not in File 8994: ",RPCNAME Q
 S FOUND=0,K=""
 F  S K=$O(^DIC(19,CTXIEN,"RPC",K)) Q:K=""  D  Q:FOUND
 . I $P($G(^DIC(19,CTXIEN,"RPC",K,0)),"^",1)=RPCIEN S FOUND=1
 I FOUND W !,"  Already in context: ",RPCNAME Q
 S MAX=$O(^DIC(19,CTXIEN,"RPC",""),-1)+1
 S ^DIC(19,CTXIEN,"RPC",MAX,0)=RPCIEN
 S ^DIC(19,CTXIEN,"RPC","B",RPCIEN,MAX)=""
 W !,"  Added to context: ",RPCNAME
 Q
