ZVEPROB ;VE;probe RPCs in File 8994 (+ DDR family);2026-03-21
 ; Copy into running VistA r/ and run: mumps -r PROBE^ZVEPROB
 ;
PROBE ;Check if specific RPCs exist in ^XWB(8994)
 N NAME,IEN,LIST,I
 S LIST(1)="PSB MED LOG"
 S LIST(2)="PSB ALLERGY"
 S LIST(3)="PSJBCMA"
 S LIST(4)="PSB VALIDATE ORDER"
 S LIST(5)="DGPM NEW ADMISSION"
 S LIST(6)="DGPM NEW TRANSFER"
 S LIST(7)="DGPM NEW DISCHARGE"
 S LIST(8)="GMRIO RESULTS"
 S LIST(9)="GMRIO ADD"
 S LIST(10)="GMPL ADD SAVE"
 S LIST(11)="ORWPCE SAVE"
 S LIST(12)="LR ORDER"
 S LIST(13)="PX SAVE DATA"
 S LIST(14)="ORWDX SAVE"
 S LIST(15)="ORWDXA DC"
 S LIST(16)="ORWDXA COMPLETE"
 S LIST(17)="ORWDXA FLAG"
 S LIST(18)="ORWDXA HOLD"
 S LIST(19)="MAG4 ADD IMAGE"
 S LIST(20)="SDEC APPADD"
 S LIST(21)="SDOE LIST ENCOUNTERS"
 S LIST(22)="PSO UPDATE MED LIST"
 S LIST(23)="PSJ LM ORDER UPDATE"
 S LIST(24)="DG ADT DISCHARGE"
 S LIST(25)="NURS TASK LIST"
 S LIST(26)="NURS ASSESSMENTS"
 S LIST(27)="ZVENAS LIST"
 S LIST(28)="TIU CREATE RECORD"
 S LIST(29)="TIU SET DOCUMENT TEXT"
 S LIST(30)="TIU DOCUMENTS BY CONTEXT"
 S LIST(31)="ORWPS ACTIVE"
 S LIST(32)="ORQQAL LIST"
 S LIST(33)="ORWDXC ACCEPT"
 ; DDR family (direct-write / tenant-admin)
 S LIST(34)="DDR FILER"
 S LIST(35)="DDR VALIDATOR"
 S LIST(36)="DDR DELETE ENTRY"
 S LIST(37)="DDR GETS ENTRY DATA"
 S LIST(38)="DDR LISTER"
 S LIST(39)="DDR FIND1"
 S LIST(40)="DDR LOCK NODE"
 S LIST(41)="DDR UNLOCK NODE"
 F I=1:1:41 D
 . S NAME=LIST(I)
 . S IEN=$O(^XWB(8994,"B",NAME,""))
 . I IEN W NAME,"  ->  IEN:",IEN,!
 . I 'IEN W NAME,"  ->  NOT IN FILE 8994",!
 Q
